service: importproduct

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  profile: administrator
  region: eu-west-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:ListBucket"
            - "s3:*"
            - "s3:PutObject"
            - "s3:PutObjectAcl"
          Resource:
            - "arn:aws:s3:::importproduct"
            - "arn:aws:s3:::importproduct/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: /import
          method: get
          request: 
            parameters:
              querystrings:
                name: true 
     
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: importproduct
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
          existing: true
          
          
          
          
          
